const colors = {
  primary: '#2563eb', // Modern blue
  secondary: '#3b82f6',
  success: '#10b981',
  error: '#ef4444',
  background: '#f8fafc',
  card: '#ffffff',
  text: '#1e293b',
  textLight: '#64748b',
  border: '#e2e8f0',
};

const styles = {
  // Home page styles
  container: {
    textAlign: 'center',
    padding: '40px 20px',
    backgroundColor: colors.background,
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: '3.5rem',
    color: colors.text,
    marginBottom: '1rem',
    fontWeight: 'bold',
    background: 'linear-gradient(45deg, #2563eb, #3b82f6)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  subtitle: {
    fontSize: '1.5rem',
    color: colors.textLight,
    marginBottom: '2rem',
    maxWidth: '600px',
    lineHeight: '1.5',
  },
  buttonContainer: {
    display: 'flex',
    gap: '20px',
    marginTop: '30px',
  },
  button: {
    padding: '12px 32px',
    fontSize: '1.1rem',
    cursor: 'pointer',
    backgroundColor: colors.primary,
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 6px rgba(37, 99, 235, 0.1)',
    '&:hover': {
      transform: 'translateY(-2px)',
      backgroundColor: colors.secondary,
      boxShadow: '0 6px 8px rgba(37, 99, 235, 0.2)',
    },
  },
  footer: {
    marginTop: 'auto',
    padding: '20px',
    color: colors.textLight,
    borderTop: `1px solid ${colors.border}`,
    width: '100%',
    textAlign: 'center',
  },

  // Trade page styles
  tradeContainer: {
    padding: '40px 20px',
    backgroundColor: colors.background,
    minHeight: '100vh',
  },
  tradeCard: {
    backgroundColor: colors.card,
    borderRadius: '16px',
    boxShadow: '0 10px 25px rgba(0, 0, 0, 0.05)',
    maxWidth: '800px',
    margin: '0 auto',
    padding: '32px',
  },
  tradeHeader: {
    fontSize: '2rem',
    color: colors.text,
    marginBottom: '32px',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  tradeForm: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '20px',
    padding: '20px',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  label: {
    fontSize: '0.9rem',
    color: colors.textLight,
    marginBottom: '4px',
  },
  input: {
    padding: '12px 16px',
    fontSize: '1rem',
    borderRadius: '8px',
    border: `1px solid ${colors.border}`,
    transition: 'all 0.3s ease',
    backgroundColor: colors.background,
    color: colors.text,
    '&:focus': {
      outline: 'none',
      borderColor: colors.primary,
      boxShadow: '0 0 0 3px rgba(37, 99, 235, 0.1)',
    },
  },
  select: {
    padding: '12px 16px',
    fontSize: '1rem',
    borderRadius: '8px',
    border: `1px solid ${colors.border}`,
    transition: 'all 0.3s ease',
    backgroundColor: colors.background,
    color: colors.text,
    cursor: 'pointer',
    '&:focus': {
      outline: 'none',
      borderColor: colors.primary,
      boxShadow: '0 0 0 3px rgba(37, 99, 235, 0.1)',
    },
  },
  submitButton: {
    gridColumn: '1 / -1',
    padding: '16px 32px',
    fontSize: '1.1rem',
    fontWeight: '600',
    cursor: 'pointer',
    backgroundColor: colors.success,
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 6px rgba(16, 185, 129, 0.1)',
    '&:hover': {
      transform: 'translateY(-2px)',
      boxShadow: '0 6px 8px rgba(16, 185, 129, 0.2)',
    },
  },
  errorMessage: {
    color: '#ef4444',
    fontSize: '0.9rem',
    marginTop: '4px',
  },
  successMessage: {
    color: colors.success,
    fontSize: '0.9rem',
    marginTop: '4px',
  },

  // Authentication pages styles
  authContainer: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '20px',
    backgroundColor: colors.background,
  },
  authCard: {
    backgroundColor: colors.card,
    borderRadius: '16px',
    boxShadow: '0 10px 25px rgba(0, 0, 0, 0.05)',
    width: '100%',
    maxWidth: '480px',
    padding: '40px',
  },
  authHeader: {
    textAlign: 'center',
    marginBottom: '32px',
  },
  authTitle: {
    fontSize: '2.5rem',
    color: colors.text,
    marginBottom: '8px',
    fontWeight: 'bold',
    background: 'linear-gradient(45deg, #2563eb, #3b82f6)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  authSubtitle: {
    fontSize: '1.1rem',
    color: colors.textLight,
  },
  authForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  authButton: {
    padding: '14px 24px',
    fontSize: '1.1rem',
    fontWeight: '600',
    cursor: 'pointer',
    backgroundColor: colors.primary,
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    transition: 'all 0.3s ease',
    marginTop: '10px',
    boxShadow: '0 4px 6px rgba(37, 99, 235, 0.1)',
    '&:hover': {
      transform: 'translateY(-2px)',
      backgroundColor: colors.secondary,
      boxShadow: '0 6px 8px rgba(37, 99, 235, 0.2)',
    },
  },
  authLinks: {
    marginTop: '20px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '16px',
  },
  authLink: {
    color: colors.primary,
    textDecoration: 'none',
    fontSize: '0.95rem',
    transition: 'color 0.3s ease',
    '&:hover': {
      color: colors.secondary,
    },
  },
  authLinkSecondary: {
    color: colors.textLight,
    textDecoration: 'none',
    fontSize: '0.95rem',
    transition: 'color 0.3s ease',
    '&:hover': {
      color: colors.text,
    },
  },
  authDivider: {
    width: '100%',
    textAlign: 'center',
    borderBottom: `1px solid ${colors.border}`,
    lineHeight: '0.1em',
    margin: '20px 0',
  },
  authDividerText: {
    background: colors.card,
    padding: '0 10px',
    color: colors.textLight,
    fontSize: '0.95rem',
  },

  // Dashboard styles
  dashboardContainer: {
    padding: '32px',
    backgroundColor: colors.background,
    minHeight: '100vh',
  },
  dashboardSection: {
    marginBottom: '40px',
  },
  sectionTitle: {
    fontSize: '1.8rem',
    color: colors.text,
    marginBottom: '24px',
    fontWeight: 'bold',
  },
  portfolioGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '24px',
    marginBottom: '40px',
  },
  portfolioCard: {
    backgroundColor: colors.card,
    padding: '24px',
    borderRadius: '12px',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.05)',
    transition: 'transform 0.3s ease',
    '&:hover': {
      transform: 'translateY(-4px)',
    },
  },
  portfolioValue: {
    fontSize: '2rem',
    fontWeight: 'bold',
    marginTop: '8px',
    color: colors.text,
  },
  cryptoTable: {
    backgroundColor: colors.card,
    borderRadius: '12px',
    overflow: 'hidden',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.05)',
  },
  tableHeader: {
    display: 'grid',
    gridTemplateColumns: '2fr 1fr 1fr 1fr 1fr',
    padding: '16px 24px',
    backgroundColor: colors.background,
    borderBottom: `1px solid ${colors.border}`,
  },
  tableHeaderCell: {
    color: colors.textLight,
    fontWeight: '600',
    fontSize: '0.9rem',
  },
  tableRow: {
    display: 'grid',
    gridTemplateColumns: '2fr 1fr 1fr 1fr 1fr',
    padding: '16px 24px',
    borderBottom: `1px solid ${colors.border}`,
    transition: 'background-color 0.3s ease',
    '&:hover': {
      backgroundColor: colors.background,
    },
  },
  tableCell: {
    display: 'flex',
    alignItems: 'center',
  },
  cryptoInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  cryptoIcon: {
    width: '32px',
    height: '32px',
    borderRadius: '50%',
  },
  cryptoName: {
    fontWeight: '600',
    color: colors.text,
  },
  cryptoSymbol: {
    color: colors.textLight,
    fontSize: '0.9rem',
  },
  tradeButton: {
    padding: '8px 16px',
    backgroundColor: colors.primary,
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    '&:hover': {
      backgroundColor: colors.secondary,
      transform: 'translateY(-2px)',
    },
  },
  forecastGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
    gap: '24px',
  },
  forecastCard: {
    backgroundColor: colors.card,
    padding: '24px',
    borderRadius: '12px',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.05)',
  },
  forecastHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '20px',
  },
  forecastIcon: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
  },
  forecastContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  forecastItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 0',
    borderBottom: `1px solid ${colors.border}`,
  },
  loadingContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '100vh',
    gap: '16px',
    backgroundColor: colors.background,
  },
  loadingSpinner: {
    width: '40px',
    height: '40px',
    border: `4px solid ${colors.border}`,
    borderTop: `4px solid ${colors.primary}`,
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
  '@keyframes spin': {
    '0%': { transform: 'rotate(0deg)' },
    '100%': { transform: 'rotate(360deg)' },
  },
  helperText: {
    fontSize: '0.85rem',
    color: colors.textLight,
    marginTop: '4px',
  },

  // Layout styles
  layoutContainer: {
    display: 'flex',
    minHeight: '100vh',
    position: 'relative',
  },
  mainContent: {
    flex: 1,
    backgroundColor: colors.background,
    minHeight: '100vh',
    transition: 'margin-left 0.3s ease',
    padding: '32px',
    boxSizing: 'border-box',
  },

  // Sidebar styles
  sidebar: {
    position: 'fixed',
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: colors.card,
    borderRight: `1px solid ${colors.border}`,
    display: 'flex',
    flexDirection: 'column',
    padding: '24px 16px',
    zIndex: 1000,
    transition: 'width 0.3s ease',
    overflow: 'hidden',
  },
  sidebarHeader: {
    marginBottom: '32px',
  },
  sidebarTitleContainer: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: '24px',
  },
  collapseButton: {
    backgroundColor: 'transparent',
    border: 'none',
    color: colors.textLight,
    cursor: 'pointer',
    fontSize: '1.2rem',
    padding: '8px',
    borderRadius: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.3s ease',
    '&:hover': {
      backgroundColor: 'rgba(37, 99, 235, 0.1)',
      color: colors.primary,
    },
  },
  sidebarTitle: {
    fontSize: '1.8rem',
    fontWeight: 'bold',
    color: colors.text,
    margin: 0,
    background: 'linear-gradient(45deg, #2563eb, #3b82f6)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  userInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px',
    backgroundColor: colors.background,
    borderRadius: '12px',
  },
  userAvatar: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    backgroundColor: colors.primary,
    color: 'white',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1.2rem',
    fontWeight: 'bold',
  },
  userName: {
    color: colors.text,
    fontWeight: '500',
  },
  sidebarNav: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  sidebarLink: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 16px',
    borderRadius: '8px',
    textDecoration: 'none',
    color: colors.textLight,
    transition: 'all 0.3s ease',
    fontSize: '1rem',
    '&:hover': {
      backgroundColor: 'rgba(37, 99, 235, 0.05)',
      color: colors.primary,
    },
  },
  sidebarIcon: {
    fontSize: '1.2rem',
    width: '24px',
    textAlign: 'center',
  },
  sidebarFooter: {
    borderTop: `1px solid ${colors.border}`,
    paddingTop: '24px',
  },
  logoutButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 16px',
    width: '100%',
    backgroundColor: 'transparent',
    border: 'none',
    borderRadius: '8px',
    color: colors.textLight,
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    fontSize: '1rem',
    '&:hover': {
      backgroundColor: 'rgba(239, 68, 68, 0.1)',
      color: '#ef4444',
    },
  },

  // Additional Trade page styles

  // Settings page styles
  settingsCard: {
    backgroundColor: colors.card,
    borderRadius: '16px',
    padding: '32px',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.05)',
  },
  settingsForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '32px',
  },
  settingsSection: {
    borderBottom: `1px solid ${colors.border}`,
    paddingBottom: '24px',
  },
  settingsSectionTitle: {
    fontSize: '1.25rem',
    color: colors.text,
    marginBottom: '20px',
    fontWeight: '600',
  },
  checkboxGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  checkboxLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    color: colors.text,
    cursor: 'pointer',
    fontSize: '1rem',
  },
  checkbox: {
    width: '18px',
    height: '18px',
    cursor: 'pointer',
  },
  pnlPercentage: {
    fontSize: '0.85rem',
    marginLeft: '8px',
    opacity: 0.8,
  },

  // Market page styles
  marketContainer: {
    padding: '24px',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  marketHeader: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    marginBottom: '24px',
  },
  marketHeaderTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  marketTitle: {
    fontSize: '2rem',
    fontWeight: 'bold',
    color: '#1e293b',
  },
  marketGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 320px',
    gap: '24px',
    height: 'calc(100vh - 200px)',
  },
  chartCard: {
    backgroundColor: 'white',
    borderRadius: '16px',
    padding: '24px',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.05)',
    height: '100%',
  },
  chartContainer: {
    height: '100%',
  },
  marketList: {
    backgroundColor: 'white',
    borderRadius: '16px',
    padding: '16px',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.05)',
    overflowY: 'auto',
  },
  coinItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    '&:hover': {
      backgroundColor: 'rgba(37, 99, 235, 0.05)',
    },
  },
  coinInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  coinIcon: {
    width: '32px',
    height: '32px',
  },
  coinDetails: {
    display: 'flex',
    flexDirection: 'column',
  },
  coinName: {
    fontWeight: '600',
    color: '#1e293b',
  },
  coinSymbol: {
    color: '#64748b',
    fontSize: '0.875rem',
  },
  coinPrice: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  currentPrice: {
    fontWeight: '600',
    color: '#1e293b',
  },
  priceChange: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: '0.875rem',
  },
  changeIcon: {
    width: '12px',
    height: '12px',
  },

  // Add these new styles to the existing styles object
  alertSection: {
    position: 'relative',
    marginBottom: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  createAlertButton: {
    backgroundColor: '#2563eb',
    color: 'white',
    padding: '8px 16px',
    borderRadius: '8px',
    border: 'none',
    cursor: 'pointer',
    fontSize: '0.9rem',
    fontWeight: '500',
    transition: 'all 0.2s ease',
    '&:hover': {
      backgroundColor: '#1d4ed8',
    },
  },
  alertFormOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  alertForm: {
    backgroundColor: 'white',
    padding: '24px',
    borderRadius: '12px',
    width: '90%',
    maxWidth: '400px',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
  },
  alertFormTitle: {
    fontSize: '1.25rem',
    fontWeight: '600',
    marginBottom: '20px',
    color: '#1e293b',
  },
  alertFormGroup: {
    marginBottom: '16px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  alertSelect: {
    width: '100%',
    padding: '8px 12px',
    borderRadius: '6px',
    border: '1px solid #e2e8f0',
    marginTop: '4px',
  },
  alertInput: {
    width: '100%',
    padding: '8px 12px',
    borderRadius: '6px',
    border: '1px solid #e2e8f0',
    marginTop: '4px',
  },
  alertFormButtons: {
    display: 'flex',
    gap: '12px',
    marginTop: '24px',
  },
  alertSubmitButton: {
    flex: 1,
    padding: '10px',
    backgroundColor: '#2563eb',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    '&:hover': {
      backgroundColor: '#1d4ed8',
    },
  },
  alertCancelButton: {
    flex: 1,
    padding: '10px',
    backgroundColor: '#e2e8f0',
    color: '#1e293b',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    '&:hover': {
      backgroundColor: '#cbd5e1',
    },
  },
  activeAlerts: {
    marginTop: '12px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  alertItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    backgroundColor: 'rgba(37, 99, 235, 0.1)',
    padding: '8px 12px',
    borderRadius: '6px',
    fontSize: '0.9rem',
  },
  alertText: {
    color: '#1e293b',
  },
  alertRemoveButton: {
    backgroundColor: 'transparent',
    border: 'none',
    color: '#64748b',
    cursor: 'pointer',
    fontSize: '1.2rem',
    padding: '0 4px',
    '&:hover': {
      color: '#ef4444',
    },
  },

  // Add these new styles to your existing styles object
  timeframeControls: {
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
  },

  countdownContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    padding: '8px 16px',
    borderRadius: '8px',
    border: '1px solid #e2e8f0',
  },

  countdownLabel: {
    fontSize: '0.75rem',
    color: '#64748b',
    marginBottom: '2px',
  },

  countdownTimer: {
    fontSize: '1.125rem',
    fontWeight: '600',
    color: '#2563eb',
    fontFamily: 'monospace',
  },

  timeframeSelector: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
  },

  timeframeButton: {
    padding: '8px 16px',
    borderRadius: '8px',
    border: '2px solid #2563eb',
    cursor: 'pointer',
    fontWeight: '600',
    transition: 'all 0.2s ease',
    '&:hover': {
      backgroundColor: '#2563eb',
      color: 'white',
    },
  },
};

export default styles;
